app:
  title: "~ Limited どこでもドア ~"
  keys:
  - "f807550bcbd47a0947a7edf6b45d957bd9a258e1434cd0949e8dcd5bc1313bde"

groups:

- title: "C/C++"
  items:
  - title: "C/C++ 参考手册"
    url: https://zh.cppreference.com/w/%E9%A6%96%E9%A1%B5
  - title: "C++ Core Guidelines"
    url: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines
  - title: "Google C++ 风格指南"
    url: https://zh-google-styleguide.readthedocs.io/en/latest/google-cpp-styleguide/contents/
  - title: "CMake Reference"
    url: https://cmake.org/cmake/help/latest/index.html
  - title: "xmake 文档仓库"
    url: https://github.com/xmake-io/xmake-docs/tree/master/zh-cn
  - title: "xrepo Windows 包"
    url: https://xrepo.xmake.io/#/packages/windows

- title: "Python"
  items:
  - title: "Python 官方文档"
    url: https://docs.python.org/zh-cn/3/index.html
  - title: "Matplotlib"
    url: https://matplotlib.org/
  - title: "Jinja2 模板设计者文档"
    url: https://docs.jinkan.org/docs/jinja2/templates.html
  - title: "scikit-learn User Guide"
    url: https://scikit-learn.org/stable/user_guide.html
  - title: "PyTorch documentation"
    url: https://pytorch.org/docs/stable/index.html

- title: "Rust"
  items:
  - title: "Rust"
    url: https://www.rust-lang.org/
  - title: "Rust 程序设计语言"
    url: https://kaisery.github.io/trpl-zh-cn/
  - title: "The Cargo Book"
    url: https://doc.rust-lang.org/cargo/index.html
  - title: "crates.io"
    url: https://crates.io/

- title: "Web/JavaScript"
  items:
  - title: "MDN Web Docs"
    url: https://developer.mozilla.org/zh-CN/
  - title: "Vue.js 文档"
    url: https://cn.vuejs.org/guide/introduction.html
  - title: "Vite 官方中文文档"
    url: https://cn.vitejs.dev/guide/
  - title: "npm"
    url: https://www.npmjs.com/

- title: "其它文档"
  items:
  - title: "Ansible.Builtin Collection"
    url: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/index.html
  - title: "Linux man pages online"
    url: https://man7.org/linux/man-pages/index.html
  - title: "ZeroMQ Documentation"
    url: https://zeromq.org/get-started/

- title: "Linux"
  items:
  - title: "Debian"
    url: https://www.debian.org/
  - title: "Debian 软件包搜索"
    url: https://www.debian.org/distrib/packages#search_packages
  - title: "ArchWiki"
    url: https://wiki.archlinux.org/

- title: "软件镜像站"
  items:
  - title: "TUNA"
    url: https://mirrors.tuna.tsinghua.edu.cn/
  - title: "USTC"
    url: https://mirrors.ustc.edu.cn/
  - title: "USTC LUG's repo file generator"
    url: https://mirrors.ustc.edu.cn/repogen/
  - title: "校园网联合镜像站"
    url: https://mirrors.cernet.edu.cn/list
  # - title: "MirrorZ"
  #   url: https://mirrorz.org/

- title: "SWPU 校外服务"
  items:
  - title: 服务门户
    url: "https://my.swpu.edu.cn/EIP/nonlogin/homePage.htm"
  - title: "学校首页"
    url: "https://www-swpu-edu-cn-s.vpn.swpu.edu.cn:8118/"
  - title: 教务系统
    url: "https://jwxt-swpu-edu-cn.vpn.swpu.edu.cn:8118/"
  - title: 教务信息化应用平台
    url: "https://deanapp-swpu-edu-cn-s.vpn.swpu.edu.cn:8118/"

- title: "常用软件"
  items:
  - title: "Visual Studio Code"
    url: https://code.visualstudio.com/
  - title: "Pot"
    url: https://github.com/pot-app/pot-desktop
  - title: "Logseq"
    url: https://logseq.com/
  - title: "Joplin"
    url: https://github.com/laurent22/joplin

- title: "About"
  items:
  - title: "simple-portal"
    url: https://github.com/CYTMWIA/simple-portal
  - title: "simple-portal-config"
    url: https://github.com/CYTMWIA/simple-portal-config
  - title: "CYTMWIA"
    url: https://github.com/CYTMWIA
  - title: "CYTMWIA's Blog"
    url: https://cytmwia.com/
